### PR TITLE
fix: fix CoW in Windows

### LINKED ISSUE #7186: pnpm 8.9.0 broken for windows dev drivers (ReFS)
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.9.0

### Which area(s) of pnpm are affected? (leave empty if unsure)

Store

### Link to the code that reproduces this issue or a replay of the bug

_No response_

### Reproduction steps

running pnpm i: (sometimes fails with below message)
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/firebase/10.4.0: 6,06 MB/6,06 MB, done
Downloading registry.npmjs.org/@firebase/firestore/4.2.0: 6,52 MB/6,52 MB, done
Downloading registry.npmjs.org/googleapis/126.0.1: 10,28 MB/10,28 MB, done
Downloading registry.npmjs.org/typescript/5.1.6: 7,15 MB/7,15 MB, done
Progress: resolved 1655, reused 0, downloaded 1573, added 1655, done
 ERR_PNPM_BAD_PACKAGE_JSON  D:\repos\teve-no\task4s\node_modules\.pnpm\webpack@5.88.2_esbuild@0.19.4\node_modules\webpack\package.json: Unexpected token '', ""... is not valid JSON while parsing '' in node_modules\.pnpm\webpack@5.88.2_esbuild@0.19.4\node_modules\webpack\package.json
```

if I get past error above, I can run pnpm store status: (it reports multiple changed packages)
```
PS D:\repos\teve-no\task4s> pnpm store status
 ERR_PNPM_MODIFIED_DEPENDENCY  Packages in the store have been mutated

These packages are modified:
registry.npmjs.org/@babel/helper-define-polyfill-provider/0.4.2(@babel/core@7.22.9)
registry.npmjs.org/@babel/helper-module-transforms/7.23.0(@babel/core@7.22.5)
registry.npmjs.org/@babel/helper-module-transforms/7.23.0(@babel/core@7.22.9)
registry.npmjs.org/@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression/7.22.15(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-syntax-class-properties/7.12.13(@babel/core@7.22.9)
registry.npmjs.org/@babel/plugin-syntax-import-assertions/7.22.5(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-class-static-block/7.22.11(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-classes/7.22.15(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-computed-properties/7.22.5(@babel/core@7.22.9)
registry.npmjs.org/@babel/plugin-transform-modules-commonjs/7.23.0(@babel/core@7.22.9)
registry.npmjs.org/@babel/plugin-transform-modules-commonjs/7.23.0(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-modules-systemjs/7.23.0(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-new-target/7.22.5(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-nullish-coalescing-operator/7.22.11(@babel/core@7.22.9)
registry.npmjs.org/@babel/plugin-transform-numeric-separator/7.22.11(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-regenerator/7.22.10(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-reserved-words/7.22.5(@babel/core@7.23.0)
registry.npmjs.org/@babel/plugin-transform-typeof-symbol/7.22.5(@babel/core@7.23.0)
registry.npmjs.org/css-tree/2.2.1
registry.npmjs.org/css-tree/2.3.1
registry.npmjs.org/mdn-data/2.0.30
registry.npmjs.org/terser-webpack-plugin/5.3.9(esbuild@0.19.4)(webpack@5.88.2)
registry.npmjs.org/webpack/5.88.2(esbuild@0.18.17)
registry.npmjs.org/webpack/5.88.2(esbuild@0.19.4)
```

if I run pnpm store prune it also clears all packages in store (like there is no ref)

### Describe the Bug

The performance improvements introduced for Windows Dev Drives in 8.9.0 seems to have broken it. It works fine on dev drives with 8.8.0, but I get multiple errors as described in the Repro steps above with 8.9.0. I tried with node 18.18.0 and 20.8.0

### Expected Behavior

It works as for 8.8.0 (verified that also pruning works correctly)

### Which Node.js version are you using?

18.18.0 and 20.8.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nachoaldamav**
Closes https://github.com/pnpm/pnpm/issues/7186

---

This PR changes the package to create the reflinks from `reflink-copy` to `copy_on_write`, on Unix it is still using `reflink-copy` underneath.

In the `copy_on_write` package I have fixed a bug that occurred in ReFS file systems where if you clone the same file to different destinations at the same time (multi-threading basically), the source was modified and filled with null bytes.

The solution to this error is to open the source with the `FILE_FLAG_NO_BUFFERING` flag (https://github.com/microsoft/CopyOnWrite/issues/12#issue-1374819104).

Also, one important thing, in https://github.com/nachoaldamav/CopyOnWrite I created some Github Actions to run the tests in the specific File systems we want to test, using Google Cloud VMs.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -2,10 +2,9 @@
 
 #[macro_use]
 extern crate napi_derive;
-
+use copy_on_write::reflink_file_sync as reflink;
```
Comment (KSXGitHub) [inline src/lib.rs]: Unnecessary rename.

```suggestion
use copy_on_write::reflink_file_sync;
```

File: src/lib.rs [hunk 2]
```diff
@@ -18,7 +17,15 @@ impl Task for AsyncReflink {
...
-        match reflink_copy::reflink(&self.src, &self.dst) {
+        let src_str = self.src.to_str().ok_or_else(|| {
+          Error::from_reason("Invalid UTF-8 sequence in source path".to_string())
+        })?;
+
+        let dst_str = self.dst.to_str().ok_or_else(|| {
+          Error::from_reason("Invalid UTF-8 sequence in destination path".to_string())
+        })?;
+
+        match reflink(src_str, dst_str) {
```
Comment (KSXGitHub) [inline src/lib.rs]:
```suggestion
        match reflink_file_sync(src_str, dst_str) {
```

File: src/lib.rs [hunk 3]
```diff
@@ -47,34 +54,34 @@ pub fn reflink_task(src: String, dst: String) -> AsyncTask<AsyncReflink> {
 // Sync version
 #[napi(js_name = "reflinkFileSync")]
 pub fn reflink_sync(env: Env, src: String, dst: String) -> Result<JsNumber> {
-    let src_path = PathBuf::from(src);
-    let dst_path = PathBuf::from(dst);
-    match reflink_copy::reflink(&src_path, &dst_path) {
+    match reflink(&src, &dst) {
```
Comment (KSXGitHub) [inline src/lib.rs]: Unnecessary `&`.

```suggestion
    match reflink_file_sync(src, dst) {
```

File: src/lib.rs [hunk 4]
```diff
@@ -47,34 +54,34 @@ pub fn reflink_task(src: String, dst: String) -> AsyncTask<AsyncReflink> {
...
-    let src = std::path::Path::new("fixtures/sample.pyc");
-    let dst = std::path::Path::new("fixtures/sample.pyc.reflink");
+    let src = "fixtures/sample.pyc";
+    let dst = "fixtures/sample.pyc.reflink";
+
+    let dst_path = std::path::Path::new(dst);
 
     // Remove the destination file if it already exists
-    if dst.exists() {
+    if dst_path.exists() {
```
Comment (KSXGitHub) [inline src/lib.rs]: Panic on error.

```suggestion
    if dst_path.try_exists().unwrap() {
```

File: src/lib.rs [hunk 5]
```diff
@@ -47,34 +54,34 @@ pub fn reflink_task(src: String, dst: String) -> AsyncTask<AsyncReflink> {
...
         std::fs::remove_file(&dst).unwrap();
     }
 
     // Run the reflink operation
-    let result = reflink_copy::reflink(&src, &dst);
+    let result = reflink(&src, &dst);
```
Comment (KSXGitHub) [inline src/lib.rs]:
```suggestion
    let result = reflink_file_sync(src, dst);
```

File: src/lib.rs [hunk 6]
```diff
@@ -47,34 +54,34 @@ pub fn reflink_task(src: String, dst: String) -> AsyncTask<AsyncReflink> {
...
     assert!(result.is_ok());
 
-    println!("Reflinked '{}' -> '{}'", src.display(), dst.display());
+    println!("Reflinked '{}' -> '{}'", src, dst);
```
Comment (KSXGitHub) [inline src/lib.rs]:
```suggestion
    println!("Reflinked {src:?} -> {dst:?}");
```

**Comment by KSXGitHub** [comment]
@nachoaldamav Since you are the author of `copy_on_write`, can you make it accept `impl AsRef<Path>` (instead of `&str`) as function parameters?

File: src/lib.rs [hunk 7]
```diff
@@ -18,7 +17,15 @@ impl Task for AsyncReflink {
...
 
     fn compute(&mut self) -> Result<Self::Output> {
-        match reflink_copy::reflink(&self.src, &self.dst) {
+        let src_str = self.src.to_str().ok_or_else(|| {
+          Error::from_reason("Invalid UTF-8 sequence in source path".to_string())
+        })?;
+
+        let dst_str = self.dst.to_str().ok_or_else(|| {
+          Error::from_reason("Invalid UTF-8 sequence in destination path".to_string())
+        })?;
```
Comment (KSXGitHub) [inline src/lib.rs]: This part of the code would not exist if `copy_on_write` accepts `Path` as parameters.

**Comment by nachoaldamav** [comment]
> @nachoaldamav Since you are the author of `copy_on_write`, can you make it accept `impl AsRef<Path>` (instead of `&str`) as function parameters?

@KSXGitHub Yes, I'll change it

**Comment by KSXGitHub** [comment]
I have also noticed that `copy_on_write` uses EUPL-1.2 license. Is this a strong license or a weak license? Is it compatible with MIT?

**Comment by nachoaldamav** [comment]
> I have also noticed that `copy_on_write` uses EUPL-1.2 license. Is this a strong license or a weak license? Is it compatible with MIT?

It's permissive, but I'm changing it to MIT, to avoid any issue

**Comment by KSXGitHub** [comment]
CI failed. Probably because of reference error caused by my suggestions failing to cover all necessary changes.

**Comment by nachoaldamav** [comment]
> CI failed. Probably because of reference error caused by my suggestions failing to cover all necessary changes.

Yes, I'm working on the other side

**Comment by nachoaldamav** [comment]
@KSXGitHub is this correct? I don't know if the `.clone()` may be wrong
```rust
// Sync version
#[napi(js_name = "reflinkFileSync")]
pub fn reflink_sync(env: Env, src: String, dst: String) -> Result<JsNumber> {
    let src_path = src.clone();
    let dst_path = dst.clone();
    match reflink_file_sync(src_path, dst_path) {
        Ok(_) => Ok(env.create_int32(0)?),
        Err(err) => Err(Error::from_reason(format!(
            "{}, reflink '{}' -> '{}'",
            err.to_string(),
            src,
            dst
        ))),
    }
}
```

**Comment by KSXGitHub** [comment]
@nachoaldamav Why didn't you pass it by reference?

File: src/lib.rs [hunk 8]
```diff
@@ -46,15 +37,13 @@ impl Task for AsyncReflink {
...
 pub fn reflink_task(src: String, dst: String) -> AsyncTask<AsyncReflink> {
-    let src_path = PathBuf::from(src);
-    let dst_path = PathBuf::from(dst);
-    AsyncTask::new(AsyncReflink { src: src_path, dst: dst_path })
+    AsyncTask::new(AsyncReflink { src, dst })
 }
 
 // Sync version
 #[napi(js_name = "reflinkFileSync")]
 pub fn reflink_sync(env: Env, src: String, dst: String) -> Result<JsNumber> {
```
Comment (KSXGitHub) [inline src/lib.rs:45]: I am not familiar with napi, can `reflink_sync` here can take `&str` as type for `src` and `dst`?

File: src/lib.rs [hunk 9]
```diff
@@ -46,15 +37,13 @@ impl Task for AsyncReflink {
 // Async version
 #[napi(js_name = "reflinkFile")]
 pub fn reflink_task(src: String, dst: String) -> AsyncTask<AsyncReflink> {
```
Comment (KSXGitHub) [inline src/lib.rs:39]: This too. Can it take `&str` as parameter types?

File: src/lib.rs (hunk 8 above)
Comment (nachoaldamav) [reply src/lib.rs:45]: I think it has to be `String`, maybe I'm missing something though https://napi.rs/docs/concepts/values.en#string

**Review by KSXGitHub — APPROVED** [review]
